Whitespace.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -3851,6 +3851,68 @@ zfs-migrate-mysql() {
     fi
 }
 
+destroy-zfs-snapshots() {
+    if ! command -v fzf > /dev/null 2>&1; then
+        error "required command missing (fzf)"
+        return 69
+    fi
+
+    local _snapshot
+
+    zfs list -H -o name -t snap \
+        | awk -F@ '{ print $2 "|" $0 }' \
+        | sort --reverse \
+        | column -t -s\| \
+        | fzf --exact --multi --no-sort --height=50% --print0 \
+        | while IFS=$'\0' read -r -d '' _snapshot; do
+
+        zfs destroy -v $(echo ${_snapshot} | cut -w -f2-64)
+    done
+}
+
+update-zfs-compression() {
+    _zfs_compression_algorithm=${1:-${ZFS_COMPRESSION_ALGORITHM}}
+
+    zfs get -H -o value,name -s local compression \
+        | awk "\$1 != \"off\" && \$1 != \"${_zfs_compression_algorithm}\" { print \$2 }" \
+        | while IFS= read -r _dataset; do
+
+        message "Updating compression for ${_dataset} to ${_zfs_compression_algorithm}"
+        zfs set compression=${_zfs_compression_algorithm} ${_dataset}
+    done
+}
+
+zfs-raid-hint() {
+    _disks=$(sysctl -n kern.disks | rs 0 1 | sort | rs 1 0)
+    _found="no"
+
+    for _disk in ${(@s/ /)_disks}; do
+        if gpart show ${_disk} 2>/dev/null | grep -q freebsd-zfs; then
+            _found="yes"
+        fi
+    done
+
+    if is-yes ${_found}; then
+        message "If using hardware RAID, you might need to run these commands:"
+        echo
+        for _disk in ${(@s/ /)_disks}; do
+            if gpart show ${_disk} 2>/dev/null | grep -q freebsd-zfs; then
+                _last_sector_offset=$(expr $(sudo diskinfo /dev/${_disk} | awk '{ print $4 }') - 1)
+                _index=$(gpart show ${_disk} 2>/dev/null | awk 'BEGIN { result = 1; } $4 == "freebsd-boot" { print $3; result = 0; exit; } END { exit result; }')
+                echo "  sysctl -q kern.geom.debugflags=0x10"
+                echo "  dd if=/dev/${_disk} of=sector.bin iseek=${_last_sector_offset}"
+                echo "  gpart recover ${_disk}"
+                echo "  gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i ${_index} ${_disk}"
+                echo "  dd if=sector.bin of=/dev/${_disk} oseek=${_last_sector_offset}"
+                echo "  sysctl -q kern.geom.debugflags=0x00"
+                echo
+            fi
+        done
+        echo "  rm sector.bin"
+        echo
+    fi
+}
+
 rc-set() {
     if [ $# -ne 3 ]; then
         usage "rc-set <file> <key> <value>"
@@ -4029,68 +4091,6 @@ config-list() {
 config-upgrade() {
     __config-upgrade-key "update_dns" "enable_update_dns"
     __config-upgrade-key "console_syslog" "enable_console_syslog"
-}
-
-destroy-zfs-snapshots() {
-    if ! command -v fzf > /dev/null 2>&1; then
-        error "required command missing (fzf)"
-        return 69
-    fi
-
-    local _snapshot
-
-    zfs list -H -o name -t snap \
-        | awk -F@ '{ print $2 "|" $0 }' \
-        | sort --reverse \
-        | column -t -s\| \
-        | fzf --exact --multi --no-sort --height=50% --print0 \
-        | while IFS=$'\0' read -r -d '' _snapshot; do
-
-        zfs destroy -v $(echo ${_snapshot} | cut -w -f2-64)
-    done
-}
-
-update-zfs-compression() {
-    _zfs_compression_algorithm=${1:-${ZFS_COMPRESSION_ALGORITHM}}
-
-    zfs get -H -o value,name -s local compression \
-        | awk "\$1 != \"off\" && \$1 != \"${_zfs_compression_algorithm}\" { print \$2 }" \
-        | while IFS= read -r _dataset; do
-
-        message "Updating compression for ${_dataset} to ${_zfs_compression_algorithm}"
-        zfs set compression=${_zfs_compression_algorithm} ${_dataset}
-    done
-}
-
-zfs-raid-hint() {
-    _disks=$(sysctl -n kern.disks | rs 0 1 | sort | rs 1 0)
-    _found="no"
-
-    for _disk in ${(@s/ /)_disks}; do
-        if gpart show ${_disk} 2>/dev/null | grep -q freebsd-zfs; then
-            _found="yes"
-        fi
-    done
-
-    if is-yes ${_found}; then
-        message "If using hardware RAID, you might need to run these commands:"
-        echo
-        for _disk in ${(@s/ /)_disks}; do
-            if gpart show ${_disk} 2>/dev/null | grep -q freebsd-zfs; then
-                _last_sector_offset=$(expr $(sudo diskinfo /dev/${_disk} | awk '{ print $4 }') - 1)
-                _index=$(gpart show ${_disk} 2>/dev/null | awk 'BEGIN { result = 1; } $4 == "freebsd-boot" { print $3; result = 0; exit; } END { exit result; }')
-                echo "  sysctl -q kern.geom.debugflags=0x10"
-                echo "  dd if=/dev/${_disk} of=sector.bin iseek=${_last_sector_offset}"
-                echo "  gpart recover ${_disk}"
-                echo "  gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i ${_index} ${_disk}"
-                echo "  dd if=sector.bin of=/dev/${_disk} oseek=${_last_sector_offset}"
-                echo "  sysctl -q kern.geom.debugflags=0x00"
-                echo
-            fi
-        done
-        echo "  rm sector.bin"
-        echo
-    fi
 }
 
 if [ $# -gt 0 ]; then
