Remove redundant quoting.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -133,7 +133,7 @@ BSDKIT_SRCDIR=$(realpath "$(dirname "$0")")
 parse_url() {
     local _url="$1"
 
-    echo "${_url}" | sed \
+    echo ${_url} | sed \
         -e "s|%%ROOT_URL%%|${BSDKIT_ROOT_URL}|g" \
         -e "s|%%VERSION%%|${BSDKIT_VERSION}|g" \
         -e "s|%%ARCH%%|${BSDKIT_ARCH}|g" \
@@ -145,19 +145,19 @@ parse_options() {
     while getopts "r:v:a:p:z:" OPT; do
         case ${OPT} in
             r)
-                BSDKIT_ROOT_URL="${OPTARG%/}"
+                BSDKIT_ROOT_URL=${OPTARG%/}
                 ;;
             v)
-                BSDKIT_VERSION="${OPTARG}"
+                BSDKIT_VERSION=${OPTARG}
                 ;;
             a)
-                BSDKIT_ARCH="${OPTARG}"
+                BSDKIT_ARCH=${OPTARG}
                 ;;
             p)
-                BSDKIT_TREE="${OPTARG}"
+                BSDKIT_TREE=${OPTARG}
                 ;;
             z)
-                BSDKIT_PKGSET="${OPTARG}"
+                BSDKIT_PKGSET=${OPTARG}
                 ;;
             *)
                 return 1
@@ -208,7 +208,7 @@ rc_get() {
     _value1=$(echo ${_buffer} | sed -E -e "s/[^=]*[[:space:]]*=//")
 
     local _value2
-    _value2=$(expr "${_value1}" : "\"\(.*\)\"")
+    _value2=$(expr ${_value1} : "\"\(.*\)\"")
 
     if [ -n "${_value2}" ]; then
         echo ${_value2}
@@ -274,13 +274,13 @@ valid_staging() {
 valid_destdir() {
     local _destdir="$1"
 
-    [ -d "${_destdir}" ] && [ "${_destdir}" != "/" ] && [ -f "${_destdir}/bin/sh" ]
+    [ -d ${_destdir} ] && [ ${_destdir} != "/" ] && [ -f ${_destdir}/bin/sh ]
 }
 
 valid_bsdkit() {
     local _bsdkit="$1"
 
-    [ -d "${_bsdkit}" ] && [ -f "${_bsdkit}/bsdkit" ]
+    [ -d ${_bsdkit} ] && [ -f ${_bsdkit}/bsdkit ]
 }
 
 valid_class() {
@@ -452,7 +452,7 @@ mbr_ufs_partition_large() {
 
     [ -d ${_destdir} ]
     [ -n "${_device}" ]
-    [ -e "/dev/${_device}" ]
+    [ -e /dev/${_device} ]
 
     # FIXME refactor
 
@@ -526,7 +526,7 @@ mbr_ufs_partition_small() {
 
     [ -d ${_destdir} ]
     [ -n "${_device}" ]
-    [ -e "/dev/${_device}" ]
+    [ -e /dev/${_device} ]
 
     # FIXME refactor
 
@@ -838,7 +838,7 @@ swap_setup() {
 }
 
 procfs_setup() {
-    if ! is_yes "${BSDKIT_PROCFS_ENABLE}"; then
+    if ! is_yes ${BSDKIT_PROCFS_ENABLE}; then
         return 0
     fi
 
@@ -852,7 +852,7 @@ procfs_setup() {
 }
 
 fdescfs_setup() {
-    if ! is_yes "${BSDKIT_FDESCFS_ENABLE}"; then
+    if ! is_yes ${BSDKIT_FDESCFS_ENABLE}; then
         return 0
     fi
 
@@ -866,7 +866,7 @@ fdescfs_setup() {
 }
 
 has_swap() {
-    [ "${BSDKIT_PART_SIZE_SWAP}" = "0" ] && return 1
+    [ ${BSDKIT_PART_SIZE_SWAP} = 0 ] && return 1
 
     return 0
 }
@@ -876,7 +876,7 @@ format_fstab() {
 
     valid_destdir ${_destdir}
 
-    local _fstab="${_destdir}/etc/fstab"
+    local _fstab=${_destdir}/etc/fstab
 
     echo "#linprocfs /compat/linux/proc linprocfs rw 0 0" >> ${_destdir}/etc/fstab
     echo "#tmpfs /compat/linux/dev/shm tmpfs rw,mode=1777 0 0" >> ${_destdir}/etc/fstab
@@ -903,16 +903,16 @@ install_release() {
         local _local_relpath_root
         local _local_relpath
 
-        local _release_tag="${BSDKIT_VERSION}-${BSDKIT_ARCH}"
+        local _release_tag=${BSDKIT_VERSION}-${BSDKIT_ARCH}
 
         _local_relpath_root="/usr/freebsd-dist"
-        _local_relpath="${_local_relpath_root}/${_release_tag}"
+        _local_relpath=${_local_relpath_root}/${_release_tag}
 
         if ! mkdir -p ${_local_relpath}; then
             _delete="yes"
 
-            _local_relpath_root="${_destdir}/freebsd-dist"
-            _local_relpath="${_local_relpath_root}/${_release_tag}"
+            _local_relpath_root=${_destdir}/freebsd-dist
+            _local_relpath=${_local_relpath_root}/${_release_tag}
 
             echo "Using ${_local_relpath_root}"
 
@@ -926,11 +926,11 @@ install_release() {
                 continue
             fi
 
-            if ! is_yes ${BSDKIT_INSTALL_KERNEL} && [ ${_package} != "${_package#kernel}" ]; then
+            if ! is_yes ${BSDKIT_INSTALL_KERNEL} && [ ${_package} != ${_package#kernel} ]; then
                 continue
             fi
 
-            if ! is_yes ${BSDKIT_INSTALL_DEBUG} && [ ${_package} != "${_package%_dbg}" ]; then
+            if ! is_yes ${BSDKIT_INSTALL_DEBUG} && [ ${_package} != ${_package%_dbg} ]; then
                 continue
             fi
 
@@ -940,17 +940,17 @@ install_release() {
 
             local _sha256_local
 
-            if [ -f "${_local_relpath}/${_filename}" ]; then
+            if [ -f ${_local_relpath}/${_filename} ]; then
                 echo "Checking: ${_filename}"
-                _sha256_local=$(${CAT_CMD} "${_local_relpath}/${_filename}" | sha256 -q)
+                _sha256_local=$(${CAT_CMD} ${_local_relpath}/${_filename} | sha256 -q)
             else
                 _sha256_local="0"
             fi
 
-            while [ "${_sha256}" != "${_sha256_local}" ]; do
+            while [ ${_sha256} != ${_sha256_local} ]; do
                 fetch -o ${_local_relpath}/${_filename} ${_relpath}/${_filename}
                 echo "Checking: ${_filename}"
-                _sha256_local=$(${CAT_CMD} "${_local_relpath}/${_filename}" | sha256 -q)
+                _sha256_local=$(${CAT_CMD} ${_local_relpath}/${_filename} | sha256 -q)
             done
         done
 
@@ -962,11 +962,11 @@ install_release() {
             continue
         fi
 
-        if ! is_yes ${BSDKIT_INSTALL_KERNEL} && [ ${_package} != "${_package#kernel}" ]; then
+        if ! is_yes ${BSDKIT_INSTALL_KERNEL} && [ ${_package} != ${_package#kernel} ]; then
             continue
         fi
 
-        if ! is_yes ${BSDKIT_INSTALL_DEBUG} && [ ${_package} != "${_package%_dbg}" ]; then
+        if ! is_yes ${BSDKIT_INSTALL_DEBUG} && [ ${_package} != ${_package%_dbg} ]; then
             continue
         fi
 
@@ -975,7 +975,7 @@ install_release() {
         fi
 
         echo "Extracting: ${_filename}"
-        ${CAT_CMD} "${_relpath}/${_filename}" | tar --unlink -xpJf - -C ${_destdir}
+        ${CAT_CMD} ${_relpath}/${_filename} | tar --unlink -xpJf - -C ${_destdir}
 
         sync
     done
@@ -1006,15 +1006,15 @@ install_release() {
 }
 
 install_resolv_conf() {
-    if [ -f /etc/resolv.conf ] && [ ! -f "${_destdir}/etc/resolv.conf" ]; then
-        install -m 644 -o root -g wheel /etc/resolv.conf "${_destdir}/etc/resolv.conf"
+    if [ -f /etc/resolv.conf ] && [ ! -f ${_destdir}/etc/resolv.conf ]; then
+        install -m 644 -o root -g wheel /etc/resolv.conf ${_destdir}/etc/resolv.conf
     fi
 }
 
 install_ca_root_nss() {
-    if [ -f /usr/local/share/certs/ca-root-nss.crt ] && [ ! -e "${_destdir}/usr/local/etc/ssl/cert.pem" ]; then
-        mkdir -p "${_destdir}/usr/local/etc/ssl"
-        install -m 644 -o root -g wheel /usr/local/share/certs/ca-root-nss.crt "${_destdir}/usr/local/etc/ssl/cert.pem"
+    if [ -f /usr/local/share/certs/ca-root-nss.crt ] && [ ! -e ${_destdir}/usr/local/etc/ssl/cert.pem ]; then
+        mkdir -p ${_destdir}/usr/local/etc/ssl
+        install -m 644 -o root -g wheel /usr/local/share/certs/ca-root-nss.crt ${_destdir}/usr/local/etc/ssl/cert.pem
     fi
 }
 
@@ -1305,10 +1305,10 @@ create_iocell() {
     command -v iocell > /dev/null 2>&1 || error "iocell not found (create_iocell)."
 
     local _uuid
-    _uuid=$(iocell create -e tag="${_tag}" host_hostname="${_tag}" "$@")
+    _uuid=$(iocell create -e tag=${_tag} host_hostname=${_tag} "$@")
 
     local _mountpoint
-    _mountpoint=$(iocell get mountpoint "${_tag}") || error "iocell could not retrieve mountpoint"
+    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint"
 
     local _destdir=${_mountpoint}/root
 
@@ -1330,13 +1330,13 @@ create_iocell_thin() {
 
     command -v iocell > /dev/null 2>&1 || error "iocell not found (create_iocell_thin)."
 
-    iocell create tag="${_tag}" host_hostname="${_tag}" "$@" || error "iocell could not create jail"
+    iocell create tag=${_tag} host_hostname=${_tag} "$@" || error "iocell could not create jail"
 
     # local _uuid
-    # _uuid=$(iocell get host_hostuuid "${_tag}") || error "iocell could not retrieve host_hostuuid"
+    # _uuid=$(iocell get host_hostuuid ${_tag}) || error "iocell could not retrieve host_hostuuid"
 
     local _mountpoint
-    _mountpoint=$(iocell get mountpoint "${_tag}") || error "iocell could not retrieve mountpoint"
+    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint"
 
     local _destdir=${_mountpoint}/root
 
@@ -1365,7 +1365,7 @@ create_iocage() {
     local _iocage_jails
     _iocage_jails=$(zfs get -H -p -o value mountpoint ${_iocage_root}/iocage/jails)
 
-    iocage create -e --name "${_jail_name}" "$@"
+    iocage create -e --name ${_jail_name} "$@"
     local _destdir=${_iocage_jails}/${_jail_name}/root
 
     [ -d ${_destdir} ] || error "iocage root does not exist (create_iocage)."
@@ -1395,7 +1395,7 @@ create_iocage_thin() {
     local _iocage_jails
     _iocage_jails=$(zfs get -H -p -o value mountpoint ${_iocage_root}/iocage/jails)
 
-    iocage create --name "${_jail_name}" "$@"
+    iocage create --name ${_jail_name} $@
     local _destdir=${_iocage_jails}/${_jail_name}/root
 
     [ -d ${_destdir} ] || error "iocage root does not exist (create_iocage)."
@@ -1438,7 +1438,7 @@ create_md() {
     local _md_device
     _md_device=$(mdconfig -a -t swap -o reserve -s 2G)
 
-    env BSDKIT_INSTALL_SRC=no FS_SWAP_SIZE=0 BSDKIT_LABEL_ROOT=mdroot "$0" deploy install_gpt_ufs "$@" small "${_md_device}"
+    env BSDKIT_INSTALL_SRC=no FS_SWAP_SIZE=0 BSDKIT_LABEL_ROOT=mdroot "$0" deploy install_gpt_ufs "$@" small ${_md_device}
 
     rm -f ${BSDKIT_DESTDIR}/etc/rc.conf
 
@@ -1461,7 +1461,7 @@ create_jail_destdir() {
 
     local _destdir=${BSDKIT_JAIL_ROOT}/${_jail_name}
 
-    if [ -d "${_destdir}" ]; then
+    if [ -d ${_destdir} ]; then
         [ "$(echo $(find ${_destdir} -type d -empty -maxdepth 0 | wc -l))" = "1" ] || error "${_destdir} already exists (create_jail_destdir)."
     fi
 
@@ -1472,8 +1472,8 @@ create_jail_destdir() {
     local _zfs="NO"
 
     if [ -n "${_parent_fs}" ]; then
-        if ! zfs get -H -o value mountpoint "${_parent_fs}/${_jail_name}" > /dev/null 2>&1; then
-            ${ZFS_CREATE_CMD} -o compression=on "${_parent_fs}/${_jail_name}"
+        if ! zfs get -H -o value mountpoint ${_parent_fs}/${_jail_name} > /dev/null 2>&1; then
+            ${ZFS_CREATE_CMD} -o compression=on ${_parent_fs}/${_jail_name}
             _zfs="YES"
         fi
     else
@@ -1496,8 +1496,8 @@ _do_configure_jail() {
 
     customize_base ${_destdir}
 
-    if [ -f /etc/hosts ] && [ ! -f "${_destdir}/etc/hosts" ]; then
-        install -m 644 -o root -g wheel /etc/hosts "${_destdir}/etc/hosts"
+    if [ -f /etc/hosts ] && [ ! -f ${_destdir}/etc/hosts ]; then
+        install -m 644 -o root -g wheel /etc/hosts ${_destdir}/etc/hosts
     fi
 
     start_jail ${_destdir}
@@ -1516,7 +1516,9 @@ remove_jail() {
 
     valid_destdir ${_destdir}
 
-    local _dirname="$(dirname ${_destdir})"
+    local _dirname
+    _dirname=$(dirname ${_destdir})
+
     local _parent_fs
     _parent_fs=$(mount -p | awk "\$2 == \"${_dirname}\" { print \$1 }")
 
@@ -1525,19 +1527,19 @@ remove_jail() {
     local _devfs
 
     mount -p -t devfs | cut -w -f 2 | while read _devfs; do
-        if [ "${_devfs}" = "${_destdir}/dev" ]; then
+        if [ ${_devfs} = ${_destdir}/dev ]; then
             umount -f ${_destdir}/dev
         fi
     done
 
     if [ -n "${_parent_fs}" ]; then
-        if zfs get -H -o value mountpoint "${_parent_fs}/${_jail_name}" > /dev/null 2>&1; then
+        if zfs get -H -o value mountpoint ${_parent_fs}/${_jail_name} > /dev/null 2>&1; then
             _zfs="YES"
         fi
     fi
 
-    if [ "${_zfs}" = "YES" ]; then
-        zfs destroy "${_parent_fs}/${_jail_name}"
+    if [ ${_zfs} = "YES" ]; then
+        zfs destroy ${_parent_fs}/${_jail_name}
     else
         rm -r -f ${_destdir} > /dev/null 2>&1 || :
         chflags -R noschg ${_destdir} > /dev/null 2>&1 || :
@@ -1781,7 +1783,7 @@ build_setup_staging() {
     mkdir -p ${_tmp}
     mount -t tmpfs tmpfs ${_tmp}
 
-    local _destdir="${_tmp}/destdir"
+    local _destdir=${_tmp}/destdir
 
     mkdir -p ${_destdir}
 
@@ -1800,7 +1802,7 @@ build_setup_staging() {
 
     echo_bsdkit_public_key > ${_destdir}/root/.ssh/authorized_keys
 
-    local _mfsroot="${_tmp}/mfsroot"
+    local _mfsroot=${_tmp}/mfsroot
 
     mkdir -p ${_mfsroot}
 
@@ -1993,7 +1995,7 @@ build_setup_iso() {
         valid_pkgpath ${_pkgpath}
     fi
 
-    local _iso_path="${_iso}.fs"
+    local _iso_path=${_iso}.fs
 
     mkdir -p ${_iso_path}
 
@@ -2020,7 +2022,7 @@ build_setup_iso() {
         mount -t msdosfs /dev/${_efiboot_md_device} ${_efiboot_root}
         {
             mkdir -p ${_efiboot_root}/efi/boot
-            cp "${_iso_path}/boot/loader.efi" ${_efiboot_root}/efi/boot/bootx64.efi
+            cp ${_iso_path}/boot/loader.efi ${_efiboot_root}/efi/boot/bootx64.efi
         }
         umount ${_efiboot_root}
 
@@ -2045,7 +2047,7 @@ build_setup_iso() {
 
     for _entry in $(etdump --format shell ${_iso}); do
         eval ${_entry}
-        if [ "${et_platform}" = "efi" ]; then
+        if [ ${et_platform} = "efi" ]; then
             _esp_start=$(expr ${et_lba} \* 2048)
             _esp_size=$(expr ${et_sectors} \* 512)
             _esp_param="-p efi::${_esp_size}:${_esp_start}"
@@ -2228,9 +2230,9 @@ EOF
         ANSIBLE_CONFIG=${_ansible_cfg} \
         SSH_AUTH_SOCK="" \
         $(environment) \
-        BSDKIT_INTERFACE="${_bsdkit_interface}" \
-        BSDKIT_IFCONFIG="${_bsdkit_ifconfig}" \
-        BSDKIT_DEFAULTROUTER="${_bsdkit_defaultrouter}" \
+        BSDKIT_INTERFACE=${_bsdkit_interface} \
+        BSDKIT_IFCONFIG=${_bsdkit_ifconfig} \
+        BSDKIT_DEFAULTROUTER=${_bsdkit_defaultrouter} \
         ansible-playbook ${BSDKIT_SRCDIR}/playbook/bsdkit.yml
 
     rm -r ${_ansible_root}
