Cleanup of jail management.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -121,9 +121,6 @@ environment()
 : ${FREEBSD_REL_URL_TEMPLATE:='%%ROOT_URL%%/release-%%VERSION%%-%%ARCH%%'}
 : ${FREEBSD_PKG_URL_TEMPLATE:='%%ROOT_URL%%/packages-${ABI}-%%TREE%%-%%PKGSET%%'}
 
-: ${IOCELL_JAILS:=/iocell/jails}
-: ${IOCAGE_JAILS:=/iocage/jails}
-
 # FREEBSD_REL_URL, FREEBSD_PKG_URL: initialized by parse_options
 
 : ${PARSE_OPTIONS_SHIFT:=0}
@@ -1309,6 +1306,7 @@ install_mbr_zfs()
     return 0
 }
 
+# bsdkit create_iocell tag -v12.1
 create_iocell()
 {
     parse_options "$@"
@@ -1322,7 +1320,8 @@ create_iocell()
     which iocell > /dev/null 2>&1 || error "iocell not found (create_iocell)."
 
     local _uuid=$(iocell create -e tag="${_tag}" host_hostname="${_tag}" "$@")
-    local _destdir=${IOCELL_JAILS}/${_uuid}/root
+    local _mountpoint=$(iocell get mountpoint "${_tag}") || error "iocell could not retrieve mountpoint"
+    local _destdir=${_mountpoint}/root
 
     [ -d ${_destdir} ] || error "iocell root does not exist (create_iocell)."
 
@@ -1331,6 +1330,7 @@ create_iocell()
     _do_configure_jail ${_destdir}
 }
 
+# bsdkit create_iocell_thin tag release=12.1-RELEASE
 create_iocell_thin()
 {
     parse_options "$@"
@@ -1343,18 +1343,18 @@ create_iocell_thin()
 
     which iocell > /dev/null 2>&1 || error "iocell not found (create_iocell_thin)."
 
-    iocell create tag="${_tag}" host_hostname="${_tag}" "$@"
+    iocell create tag="${_tag}" host_hostname="${_tag}" "$@" || error "iocell could not create jail"
 
-    local _uuid=$(iocell get host_hostuuid "${_tag}")
-    local _destdir=${IOCELL_JAILS}/${_uuid}/root
+    local _uuid=$(iocell get host_hostuuid "${_tag}") || error "iocell could not retrieve host_hostuuid"
+    local _mountpoint=$(iocell get mountpoint "${_tag}") || error "iocell could not retrieve mountpoint"
+    local _destdir=${_mountpoint}/root
 
     [ -d ${_destdir} ] || error "iocell root does not exist (create_iocell_thin)."
 
-    iocell start ${_uuid}
     _do_configure_jail ${_destdir}
-    iocell stop ${_uuid}
 }
 
+# bsdkit create_iocage -v12.1 tag
 create_iocage()
 {
     parse_options "$@"
@@ -1365,15 +1365,43 @@ create_iocage()
 
     shift
 
+    unset IOCAGE_COLOR
+
     which iocage > /dev/null 2>&1 || error "iocage not found (create_iocage)."
-
+    iocage get -p > /dev/null 2>&1 || error "unable to retrieve iocage mount point (create_iocage)."
+    local _iocage_root=$(iocage get -p)
+    local _iocage_jails=$(zfs get -H -p -o value mountpoint ${_iocage_root}/iocage/jails)
     iocage create -e --name "${_jail_name}" "$@"
-
-    local _destdir=${IOCAGE_JAILS}/${_jail_name}/root
+    local _destdir=${_iocage_jails}/${_jail_name}/root
 
     [ -d ${_destdir} ] || error "iocage root does not exist (create_iocage)."
 
     INSTALL_KERNEL=no _do_create_jail ${_destdir}
+
+    _do_configure_jail ${_destdir}
+}
+
+# bsdkit create_iocage_thin tag -r 12.1-RELEASE
+create_iocage_thin()
+{
+    parse_options "$@"
+
+    shift ${PARSE_OPTIONS_SHIFT}
+
+    local _jail_name="$1"
+
+    shift
+
+    unset IOCAGE_COLOR
+
+    which iocage > /dev/null 2>&1 || error "iocage not found (create_iocage)."
+    iocage get -p > /dev/null 2>&1 || error "unable to retrieve iocage mount point (create_iocage)."
+    local _iocage_root=$(iocage get -p)
+    local _iocage_jails=$(zfs get -H -p -o value mountpoint ${_iocage_root}/iocage/jails)
+    iocage create --name "${_jail_name}" "$@"
+    local _destdir=${_iocage_jails}/${_jail_name}/root
+
+    [ -d ${_destdir} ] || error "iocage root does not exist (create_iocage)."
 
     _do_configure_jail ${_destdir}
 }
