Add missing period to error messages.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -90,7 +90,7 @@ check_freebsd() {
 
 check_ansible() {
     if ! command -v ansible-playbook > /dev/null 2>&1; then
-        error "required command missing (ansible-playbook)"
+        error "required command missing (ansible-playbook)."
         # EX_UNAVAILABLE
         exit 69
     fi
@@ -1363,7 +1363,7 @@ create_iocell() {
     _uuid=$(iocell create -e tag=${_tag} host_hostname=${_tag} "$@")
 
     local _mountpoint
-    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint"
+    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint."
 
     local _destdir=${_mountpoint}/root
 
@@ -1387,13 +1387,13 @@ create_iocell_thin() {
 
     command -v iocell > /dev/null 2>&1 || error "iocell not found (create_iocell_thin)."
 
-    iocell create tag=${_tag} host_hostname=${_tag} "$@" || error "iocell could not create jail"
+    iocell create tag=${_tag} host_hostname=${_tag} "$@" || error "iocell could not create jail."
 
     # local _uuid
-    # _uuid=$(iocell get host_hostuuid ${_tag}) || error "iocell could not retrieve host_hostuuid"
+    # _uuid=$(iocell get host_hostuuid ${_tag}) || error "iocell could not retrieve host_hostuuid."
 
     local _mountpoint
-    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint"
+    _mountpoint=$(iocell get mountpoint ${_tag}) || error "iocell could not retrieve mountpoint."
 
     local _destdir=${_mountpoint}/root
 
@@ -2063,7 +2063,7 @@ build_setup_iso() {
     local _pkgpath=$4
 
     if ! command -v mkisofs > /dev/null 2>&1; then
-        error "required command missing (mkisofs)"
+        error "required command missing (mkisofs)."
         # EX_UNAVAILABLE
         exit 69
     fi
