Add 'make_full_jail'.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -1129,6 +1129,78 @@ make_thin_jail() {
     mkdir -p ${_destdir}/.base
 }
 
+make_full_jail() {
+    local _srcdir=$1
+    local _destdir=$2
+
+    _destdir=$(realpath ${_destdir})
+
+    [ ${_destdir} != "/" ] || error "invalid destination directory ('/')"
+    [ -d ${_destdir} ] || error "directory not found: ${_destdir}"
+    [ -d ${_destdir}/etc/rc.d ] || error "invalid destination directory (missing rc.d)"
+
+    [ -d ${_srcdir} ] || error "directory not found: ${_srcdir}"
+    [ -e ${_srcdir}/bin/sh ] || error "invalid source directory (missing /bin/sh)"
+    [ -d ${_destdir}/.base ] || error "directory not found: ${_destdir}/.base"
+
+    local _nullfs
+
+    mount -p -t nullfs | cut -w -f 2 | while read _nullfs; do
+        if [ ${_nullfs} = ${_destdir}/.base ]; then
+            umount -f ${_destdir}/.base
+        fi
+    done
+
+    local _directory_list=(
+        "boot"
+        "lib"
+        "libexec"
+        "rescue"
+        "sbin"
+        "usr/bin"
+        "usr/include"
+        "usr/lib"
+        "usr/lib32"
+        "usr/libdata"
+        "usr/libexec"
+        "usr/sbin"
+        "usr/share")
+
+    if is_yes ${BSDKIT_INSTALL_SRC}; then
+        _directory_list+="usr/src"
+    else
+        rm -f ${_destdir}/usr/src
+    fi
+
+    if is_yes ${BSDKIT_INSTALL_TESTS}; then
+        _directory_list+="usr/tests"
+    else
+        rm -f ${_destdir}/usr/tests
+    fi
+
+    pushd -q
+
+    local _directory
+
+    for _directory in ${_directory_list}; do
+        if [ -L ${_destdir}/${_directory} ] || [ -f ${_destdir}/${_directory} ]; then
+            rm -f ${_destdir}/${_directory}
+        fi
+
+        mkdir -p ${_destdir}/${_directory}
+
+        echo -n "${_directory}: "
+
+        cd ${_srcdir}/${_directory} && find . | cpio -pdu ${_destdir}/${_directory}
+    done
+
+    popd -q
+
+    run_mtree ${_destdir}
+
+    [ -d ${_destdir}/.base ] && rmdir ${_destdir}/.base
+}
+
 install_release() {
     local _opts _opts_args
 
