Improve ansible-playbook checks.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -78,6 +78,14 @@ is_efi() {
     [ "$(sysctl -n machdep.bootmethod)" = "UEFI" ]
 }
 
+check_ansible() {
+    if ! command -v ansible-playbook > /dev/null 2>&1; then
+        error "required command missing (ansible-playbook)"
+        # EX_UNAVAILABLE
+        exit 69
+    fi
+}
+
 environment() {
     echo \
         BSDKIT_DESTDIR=\"${BSDKIT_DESTDIR}\" \
@@ -1310,6 +1318,8 @@ install_mbr_zfs() {
 }
 
 create_iocell() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -1336,6 +1346,8 @@ create_iocell() {
 }
 
 create_iocell_thin() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -1362,6 +1374,8 @@ create_iocell_thin() {
 }
 
 create_iocage() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -1392,6 +1406,8 @@ create_iocage() {
 }
 
 create_iocage_thin() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -1420,6 +1436,8 @@ create_iocage_thin() {
 }
 
 create_jail() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -1436,6 +1454,8 @@ create_jail() {
 }
 
 configure_jail() {
+    check_ansible
+
     parse_options $@
 
     shift ${PARSE_OPTIONS_SHIFT}
@@ -2134,6 +2154,7 @@ build_setup_img() {
 }
 
 deploy() {
+    check_ansible
     echo "Running: $*"
 
     ${(@s/ /)@}
@@ -2143,6 +2164,8 @@ deploy() {
 }
 
 remote_deploy() {
+    check_ansible
+
     local _remote_address=""
     local _remote_port="22"
 
@@ -2220,6 +2243,8 @@ EOF
 }
 
 ansible_local_playbook() {
+    check_ansible
+
     ansible-playbook \
         --inventory localhost, \
         --connection local \
@@ -2228,6 +2253,8 @@ ansible_local_playbook() {
 }
 
 ansible_chroot_playbook() {
+    check_ansible
+
     local _ansible_root
     _ansible_root=$(mktemp -d /tmp/ansible_root.XXXXX)
 
@@ -2260,6 +2287,8 @@ EOF
 }
 
 ansible_jail_playbook() {
+    check_ansible
+
     local _ansible_root
     _ansible_root=$(mktemp -d /tmp/ansible_root.XXXXX)
 
@@ -2462,12 +2491,6 @@ purge_local_libdirs() {
     purge_libdir /usr/local/lib/ruby/vendor_ruby
     purge_libdir /usr/local/lib/perl5
 }
-
-if ! command -v ansible-playbook > /dev/null 2>&1; then
-    error "required command missing (ansible-playbook)"
-    # EX_UNAVAILABLE
-    exit 69
-fi
 
 if [ $# -gt 0 ]; then
     ${(@s/ /)@}
