Only check for mkisofs when it is actually required.

diff --git a/bsdkit b/bsdkit
--- a/bsdkit
+++ b/bsdkit
@@ -2026,6 +2026,12 @@ build_setup_iso()
     local _relpath="$3"
     local _pkgpath="$4"
 
+    if ! which mkisofs > /dev/null 2>&1; then
+	error "required command missing (mkisofs)"
+	# EX_UNAVAILABLE
+	exit 69
+    fi
+
     valid_staging ${_staging}
 
     if [ ${_relpath} != "none" ]; then
@@ -2391,12 +2397,6 @@ echo_bsdkit_public_key()
 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUde1HTbCcpmEsgtFUJZKYmrIxK+MMAAZEr0lCY1KRZOIxG75561r78kxHprU9144rMtp/2GjJJjfDoIweXh+YKnRKVj3ADPw5WHS93dJVK5vHGGv+fF1tdXlbyO29gQwwqrWbPmqvshbc9F2AOPWHmV0CuqYpZ6Sk0EzvBCVmx52uZE9Nbr19dBBk885xWVNH4U4NHuEYUhbxgcaaCtGjsJy/+wgUqCTJp6xavB73Pf207yI8ZnMzfaje0EMN2vDrupntDon3lgtpc2VFntF1DQwn0BSGD1IW1xyokdbEIPt2hCt03cbi3G/7Pl7oaVZLfctNYE7j9ooruZEZ/ovN bsdkit
 EOF
 }
-
-if ! which mkisofs > /dev/null 2>&1; then
-    error "required command missing (mkisofs)"
-    # EX_UNAVAILABLE
-    exit 69
-fi
 
 if ! which ansible-playbook > /dev/null 2>&1; then
     error "required command missing (ansible-playbook)"
